#!/bin/bash

####################################
# Script to build prod like env    #
####################################

# docker install
if [ !"$(which docker)" ]; then
	curl -sSL https://get.docker.com/ | sh
	usermod -aG docker ubuntu
fi

# docker-compose install
if [ !"$(which docker-compose)" ]; then
	curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
fi

# certbot install
apt-get install -y software-properties-common unzip python3
add-apt-repository ppa:certbot/certbot -y
apt-get update
apt-get install -y certbot

# ssm agent for ec2
mkdir -p /tmp/ssm
wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
dpkg -i amazon-ssm-agent.deb
rm amazon-ssm-agent.deb

systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent

mkdir -p certificates/web
mkdir -p certificates/api

mkdir logs
mkdir front

# entrypoint_deploy command
cp entrypoint_deploy /usr/bin/
chmod +x /usr/bin/entrypoint_deploy

cd front
mkdir static_files

# build network for containers
docker network create \
	--scope=local \
	--driver=bridge \
	fondo_network

# start running db
docker-compose up -d
