#!/bin/bash

####################################
# Script to build prod like env    #
####################################

# docker install
if [ !"$(which docker)" ]; then
	curl -sSL https://get.docker.com/ | sh
	usermod -aG docker ubuntu
fi

# docker-compose install
if [ !"$(which docker-compose)" ]; then
	curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
fi

# certbot install
apt-get install -y software-properties-common unzip python3
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install -y certbot

mkdir -p certificates/web
mkdir -p certificates/api

mkdir logs

# entrypoint_deploy command
cp entrypoint_deploy /usr/bin/
chmod +x /usr/bin/entrypoint_deploy

cd front
mkdir static_files

# start running db
docker-compose up -d fondodb
