#!/bin/bash

######################################################
# Script to deploy specified layer in current server #
######################################################

# Arguments length: 2
# 1: commit revision
# 2: layer to deploy

if [ $# -ne 2 ]
then
	echo 'Arguments: commit_revision {web|api}'
	exit 1
fi

cd /home/ubuntu/Fondo-DevOps/

COMMIT=$1
LAYER=$2

echo "Deploying ${LAYER} with commit: ${COMMIT}"

if [ $LAYER == 'api' ]
then
	ACTUAL_CONTAINER_NAME=fondo_api
	ARTIFACT_URI="https://github.com/Fonmon/Fondo-API/archive/${COMMIT}.zip"
fi

if [ $LAYER == 'web' ]
then
	ACTUAL_CONTAINER_NAME=fondo_web
	ARTIFACT_URI="https://github.com/Fonmon/Fondo-Web/archive/${COMMIT}.zip"
fi

if [ "$(docker ps -q -f name=$ACTUAL_CONTAINER_NAME)" ]; then
	echo "stopping fondo_${LAYER}"
	docker stop $ACTUAL_CONTAINER_NAME
fi

wget $ARTIFACT_URI && \
unzip Fondo-* && \
rm Fondo-*.zip

cd Fondo-*

CONTAINER_ID=$(date +%Y%m%d%H%M)

echo "Creating docker image and container with suffix: ${CONTAINER_ID}"
sh container/build-docker.sh $CONTAINER_ID && \
sh container/run-docker.sh $CONTAINER_ID 

echo "Finish deploy ${LAYER} layer"
exit 0
