#!/bin/bash
# Crontab: 0 0 * * 0 

set -x
source /etc/environment

exec &>> $HOME_FONMON/logs/cron_dump.log

DB=INSTALL_DB_NAME
ENV=INSTALL_ENV_NAME

DATE=`date '+%d-%m-%Y_%H-%M'`
YESTERDAY=$(date -d "$date -1 days" '+%d-%m-%Y_%H-%M')
FILENAME="fonmon_${DATE}.sql"
Y_FILENAME="fonmon_${YESTERDAY}.sql"

FILE_PATH=/tmp/${FILENAME}

docker exec -t fondo_db pg_dump $DB -Ufondouser > $FILE_PATH
# chown $USER_FONMON:$GROUP_FONMON $FILE_PATH

dropbox_uploader.sh upload $FILE_PATH $ENV/
rm $FILE_PATH
dropbox_uploader.sh delete $ENV/$Y_FILENAME
