#!/bin/bash

# options:
#  -a --all: install all crontab scripts
#  -d --dump: install dump script
#  -c --certificate: install certificates script
OPTS=`getopt -o adch \\
    -l all,dump,certificate,help \\
    -n 'install_crontabs' -- "$@"`

if [ $? != 0 ]; then exit 1; fi

DUMP=false
CERTIFICATE=false

DB=
ENV=

while true; do
    case $1 in 
        -a | --all)
            echo "Installing all scripts"
            DUMP=true; CERTIFICATE=true; shift
            DB=$1; shift
            ENV=$1; break
            ;;
        -d | --dump)
            echo "Installing dump script"
            DUMP=true; shift
            DB=$1; shift
            ENV=$1; shift
            ;;
        -c | --certificate)
            echo "Installing certificate script"
            CERTIFICATE=true; shift
            ;;
        *)
            break
            ;;
    esac
done

source /etc/environment

PREFIX=INSTALL
SUFFIX=NAME
VARIABLES=( DB ENV )

if [ $DUMP = true ]; then
    if [ -z $DB ] || [ -z $ENV ] || [[ $DB = *"-"* ]] || [[ $ENV = *"-"* ]]; then
        echo "bad arguments. Usage: { ( -a | --all ) || ( -d | --dump ) } <db_name> <environment>"
        exit 1
    fi

    cd $HOME_FONMON/crontabs
    cp generate-dump backup_generator

    for i in ${VARIABLES[@]}; do
        sed -i "s/${PREFIX}_${i}_${SUFFIX}/${!i}/g" backup_generator
    done
    chmod +x backup_generator
    # every 15th minute
    echo "*/15 * * * * $HOME_FONMON/crontabs/backup_generator" >> /etc/crontab
fi
if [ $CERTIFICATE = true ]; then
    cd $HOME_FONMON/crontabs
    cp renew-certificates /etc/letsencrypt/renewal-hooks/deploy
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/renew-certificates
fi
