#!/bin/bash
# sudo crontab: 0 5 1 * *

source /etc/environment

# docker stop fondo_web

cd $(find /etc/letsencrypt/live/* -type d -name "*api*")
cp *.pem $HOME_FONMON/certificates/api

cd $(find /etc/letsencrypt/live/* -type d ! -name "*api*")
cp *.pem $HOME_FONMON/certificates/web

chown -R ubuntu:ubuntu $HOME_FONMON/certificates

docker start fondo_web
