#!/bin/bash
# sudo crontab: 0 5 1 * *

set -x

source /etc/environment

exec &>> $HOME_FONMON/logs/cron_certificates.log

echo "Domain custom script: ${CERTBOT_DOMAIN}"

cd $(find /etc/letsencrypt/live/* -type d -name "*api*")
cp *.pem $HOME_FONMON/certificates/api

cd $(find /etc/letsencrypt/live/* -type d ! -name "*api*")
cp *.pem $HOME_FONMON/certificates/web

chown -R ubuntu:ubuntu $HOME_FONMON/certificates
