#!/bin/bash

####################################
# Script to build prod like env    #
####################################

if [ $# -ne 2 ]; then
    echo 'Arguments: linux_user linux_group'
    exit 1
fi

USER=$1
GROUP=$2

cd /home/$USER/Fondo-DevOps/
echo "export HOME_FONMON=$(pwd)" >> /etc/environment

git remote set-url origin git@github.com:Fonmon/Fondo-DevOps.git

# docker install
if [ -z "$(which docker)" ]; then
	curl -sSL https://get.docker.com/ | sh
	usermod -aG docker ${USER}
fi

# docker-compose install
if [ -z "$(which docker-compose)" ]; then
	curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
fi

# certbot install
apt-get install -y software-properties-common unzip python3 make
add-apt-repository ppa:certbot/certbot -y
apt-get update
apt-get install -y certbot

# ssm agent for ec2
mkdir -p /tmp/ssm
wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
dpkg -i amazon-ssm-agent.deb
rm amazon-ssm-agent.deb

systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent

cp deploy/.env.base deploy/.env

mkdir dumps
mkdir migrations
mkdir -p certificates/web
mkdir -p certificates/api
mkdir -p front/static_files
mkdir logs

chown -R ${USER}:${GROUP} $(pwd)

# entrypoint_deploy command
cp environment/entrypoint_deploy /usr/bin/
chmod +x /usr/bin/entrypoint_deploy

# semver tool
git clone https://github.com/fsaintjacques/semver-tool.git && \
    cd semver-tool && \
    make install && \
    cd .. && rm -rf semver-tool

# TODO: add verification if swap file or partition exist, otherwhise
# create a file and make it a swapfile

# FonmonBot Git user
git config --global user.name "FonmonBot"
git config --global user.email fondomontanez@gmail.com

# build network for containers
docker network create \
	--scope=local \
	--driver=bridge \
	fondo_network
