#!/bin/bash
set -x

######################################################
# Script to deploy specified layer in current server #
######################################################

# Arguments length: 2
# 1: commit revision
# 2: layer to deploy
# 3: env

if [ $# -ne 3 ]; then
    echo 'Arguments: commit_revision {web|api|mns} {master|develop}'
    exit 1
fi

source /etc/environment
cd $HOME_FONMON/deploy

COMMIT=$1
LAYER=$2
ENV=$3

echo "Deploying ${LAYER} with commit: ${COMMIT}"

if [ $LAYER == 'api' ]; then
    ACTUAL_CONTAINER_NAME=fondo_api
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-API/archive/${COMMIT}.zip"
    SUFFIX_PROJ="API"
    mkdir Fondo-Web && mkdir Fondo-MNS
fi

if [ $LAYER == 'web' ]; then
    ACTUAL_CONTAINER_NAME=fondo_web
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-Web/archive/${COMMIT}.zip"
    SUFFIX_PROJ="Web"
    mkdir Fondo-API && mkdir Fondo-MNS
fi

if [ $LAYER == 'mns' ]; then
    ACTUAL_CONTAINER_NAME=fondo_mns
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-MNS/archive/${COMMIT}.zip"
    SUFFIX_PROJ="MNS"
    mkdir Fondo-API && mkdir Fondo-Web
fi

export IMAGE_TAG=$(./../utils/versioning ${ENV} ${LAYER})

wget $ARTIFACT_URI && \
    unzip ${COMMIT}.zip && \
    rm ${COMMIT}.zip

mv Fondo-${SUFFIX_PROJ}-${COMMIT} Fondo-${SUFFIX_PROJ}

echo "Creating docker image for version: ${IMAGE_TAG}"
docker-compose build ${LAYER}

if [ "$(docker ps -a -q -f name=$ACTUAL_CONTAINER_NAME)" ]; then
    echo "stopping fondo_${LAYER}"
    docker stop $ACTUAL_CONTAINER_NAME && \
        docker rm $ACTUAL_CONTAINER_NAME
fi

echo "Starting container"
docker-compose run -d --service-ports --name ${ACTUAL_CONTAINER_NAME} ${LAYER}

if [ $LAYER == 'api' ]; then
    echo "deploy worker for api"
    if [ "$(docker ps -a -q -f name=fondo_api_worker)" ]; then
        echo "stopping fondo_api_worker"
        docker stop fondo_api_worker && \
            docker rm fondo_api_worker
    fi
    docker-compose run -d --service-ports --name fondo_api_worker api_worker worker
fi

rm -rf Fondo-*

echo "Finish deploy ${LAYER} layer"

# FonmonBot commit (version)
cd $HOME_FONMON
git commit -am "FonmonBot: .version file update" && \
    git push
exit 0
