#!/bin/bash
set -x

######################################################
# Script to deploy specified layer in current server #
######################################################

# Arguments length: 2
# 1: commit revision
# 2: layer to deploy
# 3: env

if [ $# -ne 3 ]; then
    echo 'Arguments: commit_revision {web|api} {master|develop}'
    exit 1
fi

source /etc/environment
cd $HOME_FONMON/deploy

COMMIT=$1
LAYER=$2
ENV=$3

echo "Deploying ${LAYER} with commit: ${COMMIT}"

if [ $LAYER == 'api' ]; then
    ACTUAL_CONTAINER_NAME=fondo_api
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-API/archive/${COMMIT}.zip"
    SUFFIX_PROJ="API"
    mkdir Fondo-Web
fi

if [ $LAYER == 'web' ]; then
    ACTUAL_CONTAINER_NAME=fondo_web
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-Web/archive/${COMMIT}.zip"
    SUFFIX_PROJ="Web"
    mkdir Fondo-API
fi

if [ "$(docker ps -a -q -f name=$ACTUAL_CONTAINER_NAME)" ]; then
    echo "stopping fondo_${LAYER}"
    docker stop $ACTUAL_CONTAINER_NAME && \
        docker rm $ACTUAL_CONTAINER_NAME
fi

export IMAGE_TAG=$(./../utils/versioning ${ENV} ${LAYER})

wget $ARTIFACT_URI && \
    unzip ${COMMIT}.zip && \
    rm ${COMMIT}.zip

mv Fondo-${SUFFIX_PROJ}-${COMMIT} Fondo-${SUFFIX_PROJ}

echo "Creating docker image and container for version: ${IMAGE_TAG}"

docker-compose build --no-cache ${LAYER} && \
    docker-compose run -d --name ${ACTUAL_CONTAINER_NAME} ${LAYER}

rm -rf Fondo-*

echo "Finish deploy ${LAYER} layer"

# FonmonBot commit (version)
cd $HOME_FONMON
git commit -am "FonmonBot: .version file update" && \
    git push
exit 0
