#!/bin/bash
set -x

######################################################
# Script to deploy specified layer in current server #
######################################################

# Arguments length: 2
# 1: commit revision
# 2: layer to deploy
# 3: env

if [ $# -ne 3 ]; then
    echo 'Arguments: commit_revision {web|api} {master|develop}'
    exit 1
fi

source /etc/environment
cd $HOME_FONMON

COMMIT=$1
LAYER=$2
ENV=$3

echo "Deploying ${LAYER} with commit: ${COMMIT}"

if [ $LAYER == 'api' ]; then
    ACTUAL_CONTAINER_NAME=fondo_api
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-API/archive/${COMMIT}.zip"
fi

if [ $LAYER == 'web' ]; then
    ACTUAL_CONTAINER_NAME=fondo_web
    ARTIFACT_URI="https://github.com/Fonmon/Fondo-Web/archive/${COMMIT}.zip"
fi

if [ "$(docker ps -a -q -f name=$ACTUAL_CONTAINER_NAME)" ]; then
    echo "stopping fondo_${LAYER}"
    docker stop $ACTUAL_CONTAINER_NAME && \
    docker rm $ACTUAL_CONTAINER_NAME
fi

if [ $ENV == 'master' ]; then
    HOST_APP=api-fonmon.minagle.com
else
    HOST_APP=dev-api-fonmon.minagle.com
fi

CONTAINER_ID=$(./utils/versioning ${ENV} ${LAYER})

wget $ARTIFACT_URI && \
unzip ${COMMIT}.zip && \
rm ${COMMIT}.zip

cd Fondo-*${COMMIT}

echo "Creating docker image and container with suffix: ${CONTAINER_ID}"
bash container/build-docker $CONTAINER_ID $HOST_APP && \
bash container/run-docker $CONTAINER_ID 

cd ..
rm -rf Fondo-*${COMMIT}

echo "Finish deploy ${LAYER} layer"

# TODO: make commit by FonmonBot for versioning
exit 0
