version: '2.3'
services:
  fondodb:
    image: postgres
    container_name: fondo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    expose:
      - 5432
  api:
    build:
      context: ./Fondo-API
      dockerfile: $PWD/dockerfiles/DockerfileApi
    image: fonapi_image:$IMAGE_TAG
    depends_on:
      - fondodb
    env_file: .env
    expose:
      - 8443
    volumes:
      - type: bind
        source: ../migrations/
        target: /app/fondo_api/migrations
  web:
    build:
      context: ./Fondo-Web
      dockerfile: $PWD/dockerfiles/DockerfileWeb
      args:
        HOST_APP: ${ALLOWED_HOST_DOMAIN}
    image: fonweb_image:$IMAGE_TAG
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ../front/static_files/
        target: /usr/share/nginx/html/static_files
      - type: bind
        source: ../certificates/web/
        target: /etc/nginx/certs/web
      - type: bind
        source: ../certificates/api/
        target: /etc/nginx/certs/api
networks:
  default:
    external:
      name: fondo_network
