version: '2.3'
services:
  fondodb:
    restart: always
    image: postgres
    container_name: fondo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      TZ: America/Bogota
    expose:
      - 5432
  api:
    restart: always
    build:
      context: ./Fondo-API
      dockerfile: $PWD/dockerfiles/DockerfileApi
    image: fonapi_image:$IMAGE_TAG
    depends_on:
      - fondodb
    env_file: .env
    expose:
      - 8443
    volumes:
      - type: bind
        source: ./fonmon-storage-credentials.json
        target: /app/fonmon-storage-credentials.json
  web:
    restart: always
    build:
      context: ./Fondo-Web
      dockerfile: $PWD/dockerfiles/DockerfileWeb
      args:
        HOST_APP: ${ALLOWED_HOST_DOMAIN}
    image: fonweb_image:$IMAGE_TAG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ../front/static_files/
        target: /usr/share/nginx/html/static_files
      - type: bind
        source: ../certificates/web/
        target: /etc/nginx/certs/web
      - type: bind
        source: ../certificates/api/
        target: /etc/nginx/certs/api
  mns:
    restart: always
    build:
      context: ./Fondo-MNS
      dockerfile: $PWD/dockerfiles/DockerfileMns
    image: fonmns_image:$IMAGE_TAG
    env_file: .env
    expose:
      - 9901
  api_beat:
    restart: always
    image: fonapi_image:$IMAGE_TAG
    env_file: .env
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./fonmon-storage-credentials.json
        target: /app/fonmon-storage-credentials.json

  redis:
    restart: always
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
networks:
  default:
    external:
      name: fondo_network
