#!/bin/bash

if [ $# -ne 3 ]; then
    echo 'Arguments: commit_revision {web|api|mns} {master|develop}'
    exit 1
fi

source /etc/environment

cd $HOME_FONMON
git pull origin master
./deploy/deploy-app $1 $2 $3
#&>> logs/deploy.log
