#!/bin/bash

set -x

if [ $# -ne 1 ]; then
    echo 'Arguments: recovery_file'
    exit 1
fi

source /etc/environment

RECOVERY_FILE=$1
cd $HOME_FONMON

tar -xzf $RECOVERY_FILE

# letsencrypt
cp -r recovery_files/letsencrypt/* /etc/letsencrypt

chown -R root:root /etc/letsencrypt

cd $(find /etc/letsencrypt/live/* -type d -name "*api*")
cp *.pem $HOME_FONMON/certificates/api

cd $(find /etc/letsencrypt/live/* -type d ! -name "*api*")
cp *.pem $HOME_FONMON/certificates/web

chown -R $USER_FONMON:$GROUP_FONMON $HOME_FONMON/certificates

cd $HOME_FONMON

# Fonmon files
cp recovery_files/fonmon/.env recovery_files/fonmon/fonmon-storage-credentials.json deploy/
cp -r recovery_files/fonmon/front/* front/

# Restore DB
DUMPS=($(ls recovery_files/fonmon/dumps/ | sort -r))
DUMP_DB="$(pwd)/recovery_files/fonmon/dumps/${DUMPS[0]}"

cd deploy/
source .env

mkdir Fondo-API Fondo-Web Fondo-MNS
docker-compose up -d fondodb
sleep 10
docker exec -i fondo_db psql -Ufondouser -d $POSTGRES_DATABASE < $DUMP_DB

# Tear down
cd $HOME_FONMON && rm -rf recovery_files $RECOVERY_FILE
rm -rf deploy/Fondo-API deploy/Fondo-Web deploy/Fondo-MNS
